/* 
 * File:   main.cpp
 * Author: Rogelio Hinojosa
 * Created on March 8, 2017, 1:32 PM
 * Purpose:  Calculate How many seat in a Softball Game are Sold
 */

//System Libraries
#include <iostream>  //Input - Output Library
using namespace std; //Name-space under which system libraries exist

//User Libraries

//Global Constants

//Function Prototypes

//Execution begins here
int main(int argc, char** argv) {
    //Declare variables
   float ClssA =0.15f; //Ticket cost at Class A Seats
   float ClssB =0.12f; //Ticket cost at Class B Seats
   float ClssC =0.09f; //Ticket cost at Class C Seats
   float IncmTck; //Income from Tickets generated
   float TotA, TotB, TotC ;  //Total seat sold for each class
   char  AmPeop; //Amount of People buying Tickets
   
    //Input data
   cout<<"This program calculates how many tickets";
   cout<<"for each class were sold"<<endl;
   cin>>AmPeop;
   
    //Map inputs to outputs or process the data
   TotA=ClssA*AmPeop;
   
   TotB=ClssB*AmPeop;
   
   TotC=ClssC*AmPeop;
   
   IncmTck=TotA+TotB+TotC;
           
    //Output the transformed data
   cout<<"The amount of Tickets sold for Class A = "<< TotA<<endl;
   cout<<"The amount of Tickets sold for Class B = "<< TotB<<endl;
   cout<<"The amount of Tickets sold for Class C = "<< TotC<<endl;
   cout<<"Income generated by Tickets = " << IncmTck<<endl;
   
    //Exit stage right!
    return 0;
}

